// Описание переменных окружения смотри в Readme.
const env = process.env;

module.exports = {
    MONGO_CONNECT_STRING: env.MONGO_CONNECT_STRING || 'mongodb://mongo/admin',
    BLOCKCHAIN_SUBSCRIBE_TIMEOUT: env.BLOCKCHAIN_SUBSCRIBE_TIMEOUT || 60000,
    DAY_START: env.DAY_START || 3,
    BLOCKCHAIN_NODE_ADDRESS: env.BLOCKCHAIN_NODE_ADDRESS || 'wss://ws.golos.io',
    METRICS_HOST: env.METRICS_HOST || 'localhost',
    METRICS_PORT: env.METRICS_PORT || 8125,
    GATE_LISTEN_PORT: env.GATE_LISTEN_PORT || 8080,
    SOLZHENITSYN_CONNECT_STRING: env.SOLZHENITSYN_CONNECT_STRING,
    BULGAKOV_CONNECT_STRING: env.BULGAKOV_CONNECT_STRING,
};
